#!/usr/bin/env python
# _*_ coding:utf-8 _*_
#
# @Version : 1.0
# @Time    : 2025/8/16 0:44
# @Author  : Hao Xue
# @E-mail  : studid@163.com
# @File    : SsToRNAplot.py
#
# Convert tRNA secondary structure files generated by tRNAscan-SE into a format supported by RNAplot.


import re
import sys

aa_dict = {
    # 标准氨基酸
    'Ala': 'A',  # Alanine
    'Arg': 'R',  # Arginine
    'Asn': 'N',  # Asparagine
    'Asp': 'D',  # Aspartic acid
    'Cys': 'C',  # Cysteine
    'Gln': 'Q',  # Glutamine
    'Glu': 'E',  # Glutamic acid
    'Gly': 'G',  # Glycine
    'His': 'H',  # Histidine
    'Ile': 'I',  # Isoleucine
    'Leu': 'L',  # Leucine
    'Lys': 'K',  # Lysine
    'Met': 'M',  # Methionine
    'Phe': 'F',  # Phenylalanine
    'Pro': 'P',  # Proline
    'Ser': 'S',  # Serine
    'Thr': 'T',  # Threonine
    'Trp': 'W',  # Tryptophan
    'Tyr': 'Y',  # Tyrosine
    'Val': 'V'  # Valine
}

import re

pattern = re.compile(
     r'^(.*trna(\d+) \((\d+-\d+)\).*)$' +             # ID 行
     r'(?:.*\n)+Type:\s*([A-Za-z]+)\s+Anticodon:\s*([A-Z]+).*$' +  # 类型行
     r'(?:.*\n)+Seq:\s*(.+)$' +                       # 序列行
     r'(?:.*\n)+Str:\s*(.+)$',                        # 结构行
     re.MULTILINE 
)
def cope_one(t):
    item = re.findall(pattern, t)[0]
    #print(item[0])
    return (aa_dict[item[3]],item[2],item[-2],item[-1])
ss = sys.argv[1]
with open(ss) as f:
	text = f.read()
text = text.split("\n\n")
ls = []
for i in text:
    if not i.strip():
        continue
    ls.append(cope_one(i))
aa1 = []
aa2 = []
for i in ls:
    if i[0] not in aa1:
        aa1.append(i[0])
    else:
        aa2.append(i[0])
c_aa2 = {i:1 for i in aa2}
out_ = ""
for i in ls:
    if i[0] in c_aa2:
        flag = str(c_aa2[i[0]])
        c_aa2[i[0]] += 1
    else:
        flag = ""
    out_ += ">trn"+i[0]+flag+"-"+i[1]+"\n"+i[2]+"\n"+i[3].replace(">","(").replace("<",")")+"\n"

with open("plot.ssf","w") as f:
    f.write(out_)