#!/usr/bin/env python
# _*_ coding:utf-8 _*_
#
# @Version : 1.0
# @Project : https://github.com/shueho/BioDataTools
# @Time    : 2023/7/30 13:00
# @Author  : Hao Xue
# @E-mail  : studid@163.com
# @File    : MPAtoMatrix.py
#
# Convert mpa files generated by Kraken1/2 or Bracken software into a species abundance matrix.

import os
import sys
print("Author: XueHao\nE-mail: studid@163.com")
path = sys.argv[1]
ls = os.listdir(path)
ls = [i.replace(".mpa","") for i in ls if ".mpa" in i]
print("READ mpa file: OK!")

with open(path+"/"+ls[0]+".mpa") as f:
    lt = f.readlines()
Classification = []
for i in lt[1:]:
    Classification.append(i.split("\t")[0])

main_d = dict()
for i in Classification:
    main_d[i] = []
print("READ Classification list: OK!")
HEAD = ["#Classification"] + ls
HEAD = [i.replace(".bracken","") for i in HEAD]

def readMpa(item):
    with open(item+".mpa") as f:
        tem = f.readlines()
    tem = [i.strip().split("\t") for i in tem[1:]]
    td = dict(tem)
    for i in td:
        main_d[i].append(td[i])
    print(item + ": OK!")

print("begin!")
for i in ls:
    readMpa(path+"/"+i)

with open("mpaMatrix.txt","w") as f:
    f.write("\t".join(HEAD)+"\n")
    for i in Classification:
        f.write(i+"\t"+"\t".join(main_d[i])+"\n")
print("finish!")